# Generated by Django 4.2.7 on 2023-11-26 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ancestor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentChildren',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('children', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='children', to='Ancestor.person')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parent', to='Ancestor.person')),
            ],
            options={
                'unique_together': {('parent', 'children')},
            },
        ),
    ]
