# Generated by Django 4.2.7 on 2023-12-06 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ancestor', '0003_alter_parentchildren_options_alter_person_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='parentchildren',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='parentchildren',
            constraint=models.UniqueConstraint(fields=('parent', 'children'), name='parent_children_unique_key', violation_error_message='Relation already exists'),
        ),
    ]
