# Generated by Django 4.2.7 on 2023-12-06 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ancestor', '0004_alter_parentchildren_unique_together_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='parentchildren',
            constraint=models.CheckConstraint(check=models.Q(('children', models.F('parent')), _negated=True), name='prevent_self_parenting'),
        ),
    ]
