# Generated by Django 4.2.7 on 2023-12-06 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ancestor', '0005_parentchildren_prevent_self_parenting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentchildren',
            name='children',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parent', to='Ancestor.person'),
        ),
        migrations.AlterField(
            model_name='parentchildren',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='children', to='Ancestor.person'),
        ),
    ]
