# Generated by Django 5.0 on 2023-12-28 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FamilyBranch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='person_images/'),
        ),
    ]
