# Generated by Django 5.0.1 on 2024-01-07 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FamilyBranch', '0003_alter_person_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='child_no',
            field=models.PositiveSmallIntegerField(blank=True, default=1, null=True),
        ),
    ]
